### ISSUE TITLE
Wordnet hierarchy file 

### ISSUE THREAD

**Issue by Gautamshahi** [AKSW/Cetus#9]
Hello, do you also share the  Wordnet hierarchy file like the DOLCE hierarchy which you gave?

**Comment by MichaelRoeder** [comment]
Can you please explain in more detail what exactly you expect? 

We didn't run any experiments with WordNet (at least not with WordNet itself; in the paper, you will see an example that shows that Yago included the WordNet type hierarchy).

**Comment by Gautamshahi** [comment]
Thank you for your answer. I have wordnet type for an entity as Ukraine as wordnet_physical_entity_100001930','wordnet_region_108630985','wordnet_administrative_district_108491826 Now, using the TTL file, I would like to make a type graph entity wordnet_region and administrative_district to show relation from the top level. 

I hope I make the questions clear now.

**Comment by MichaelRoeder** [comment]
We don't have this hierarchy. At the moment, I can think of two solutions:
1. You can have a look at the YAGO3 knowledge graph and check whether it contains the type hierarchy you are looking for.
2. You can look at WordNet itself. From your perspective, it already comes as a type hierarchy, i.e., hypernyms (super classes) are connected to their hyponyms (sub classes).

**Comment by Gautamshahi** [comment]
Thank you. Exactly, I did the same, but I need to link each entity to the mentioned in the figure below so that only wordnet ontology similar to DOLCE will be useful.

Going through the entire YAGO is not possible due to computational limitations.

![image](https://github.com/dice-group/Cetus/assets/3966230/cb1b5543-32f1-4051-8655-9af3082e5e17)

**Comment by MichaelRoeder** [comment]
Did you work with WordNet before? If you already have the types for your entities, it should be quite easy to get this "tree". You simply start from the synset (i.e., the node in wordnet) representing for example `administrative_district_108491826` (I think the number is some kind of ID for the synset but you would have to double check that) and recursively go up the "hierarchy" of WordNet synsets from there.

WordNet itself is not very big and you can most probably find a library for your favorite programming language to interact with it :thinking:

**Comment by Gautamshahi** [comment]
Hi,

Thanks for explaining. Yes I worked with WordNet but I am not getting the
TTL file which has same terms as from YAGO. In this paper, I found that
terms in your file related to DOLCE.

If you have the link for the WordNet TTL file that would be great.

Thanks for your help.

**Comment by MichaelRoeder** [comment]
This is nothing that you will find within this project. We only used WordNet as part of YAGO3.

If you are looking for WordNet as RDF, you may want to have a look at https://semanticweb.cs.vu.nl/lod/wn30/
